#!/bin/sh
test -n "${IF_QT_REMOTE_ADDRESS}" || exit 0
test -z "${IF_QT_NO_PRECREATE}" || exit 0
if [ -n "${IF_QT_TUN_MODE}" ] && [ "${IF_QT_TUN_MODE}" = "1" ]; then
	DEVTYPE="tun"
else
	DEVTYPE="tap"
fi
if [ -x /sbin/ip ] && /sbin/ip tuntap 2>&1 >/dev/null; then
	/sbin/ip tuntap add dev "${IFACE}" mode "${DEVTYPE}" user quicktun
else
	echo "Unable to pre-create tun/tap interface. Install iproute2 or run QuickTun as root by setting QT_NO_PRECREATE."
fi
