#!/bin/sh
test -n "${IF_QT_REMOTE_ADDRESS}" || exit 0
test -z "${IF_QT_NO_PRECREATE}" || exit 0
if [ -n "${IF_QT_TUN_MODE}" ]; then
	DEVTYPE="tun"
else
	DEVTYPE="tap"
fi
if [ -x /usr/sbin/openvpn ]; then
	/usr/sbin/openvpn --mktun --dev "${IFACE}" --dev-type "${DEVTYPE}" --user quicktun
elif [ -x /sbin/ip ]; then
	/sbin/ip tuntap add dev "${IFACE}" mode "${DEVTYPE}" user quicktun
else
	echo "Unable to pre-create tun/tap interface. Run QuickTun as root."
fi
