#!/bin/sh

set -e

case "$1" in
	purge)
		if [ -x "$(command -v deluser)" ]; then
			deluser --quiet --system quicktun > /dev/null || true
			deluser --group --system --quiet --only-if-empty quicktun || true
		else
			echo "not removing quicktun system account and group because deluser command was not found" >&2
		fi
		;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
esac
